### ISSUE TITLE
component: generic grid

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/obsidian-dnd-ui-toolkit#6]
The grid component can be used to dynamically build layouts of items. For example, you may want to build an HP tracker board for the encounter.

Implementation will probably be limited to specific components. 

Implementation should also support nesting grids within grids

**Example**

````
```grid
items:
  - state_key: monster_1
    health: 24
    type: healthpoints
  - state_key: monster_2
    health: 24
    type: healthpoints
  - state_key: monster_3
    health: 24
    type: healthpoints
  - state_key: monster_4
    health: 24
    type: healthpoints
grid:
  columns: 2
  gap: 1rem
```
````
